logLevel: info
logDestinations: [stdout]

authMethod: http
authHTTPAddress: http://control-api:8080/api/v1/media-auth
authHTTPExclude:
  - action: api
  - action: metrics

rtmp: true
rtmpAddress: :1935

hls: true
hlsAddress: :8888
hlsAllowOrigins: ["*"]

api: true
apiAddress: :9997
apiAllowOrigins: ["*"]

metrics: true
metricsAddress: :9998

pathDefaults:
  sourceOnDemand: false
  record: false
  recordPath: /recordings/%path/%Y-%m-%d/%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 1s
  recordMaxPartSize: 50M
  recordSegmentDuration: 30s
  recordDeleteAfter: 30d
